<?php
$con_str = "Data Source=dwhdb; Uid=dba; Pwd=sql;";
$query_string = "insert into dc.trig_mpbn_delta_values 
select  curr.datatime,
        curr.nodename,
        curr.ifIndex,
        curr.ifType,
        curr.ifMtu,
        curr.ifSpeed ,
        curr.ifAdminStatus,
        curr.ifOperStatus,
        curr.ifLastChange,
        curr.ifOutQLen,
        (curr.ifInMulticastPkts - prev.ifInMulticastPkts) as ifInMulticastPkts,
        (curr.ifInBroadcastPkts - prev.ifInBroadcastPkts) as ifInBroadcastPkts,
        (curr.ifOutMulticastPkts - prev.ifOutMulticastPkts) as ifOutMulticastPkts,
        (curr.ifOutBroadcastPkts - prev.ifOutBroadcastPkts) as ifOutBroadcastPkts,
        (curr.ifHCInOctets -prev.ifHCInOctets) as ifHCInOctets ,
        (curr.ifHCInUcastPkts - prev.ifHCInUcastPkts) as ifHCInUcastPkts,
        (curr.ifHCInMulticastPkts - prev.ifHCInMulticastPkts) as ifHCInMulticastPkts,
        (curr.ifHCInBroadcastPkts  - prev.ifHCInBroadcastPkts) as ifHCInBroadcastPkts ,
        (curr.ifHCOutOctets - prev.ifHCOutOctets) as ifHCOutOctets,
        (curr.ifHCOutUcastPkts  - prev.ifHCOutUcastPkts ) as ifHCOutUcastPkts ,
        (curr.ifHCOutMulticastPkts - prev.ifHCOutMulticastPkts) as ifHCOutMulticastPkts,
        (curr.ifHCOutBroadcastPkts - prev.ifHCOutBroadcastPkts) as ifHCOutBroadcastPkts,
        (curr.ifInOctets- prev.ifInOctets) as ifInOctets,
        (curr.ifInUcastPkts - prev.ifInUcastPkts) as ifInUcastPkts,
        (curr.ifInNUcastPkts - prev.ifInNUcastPkts) as ifInNUcastPkts,
        (curr.ifInDiscards  - prev.ifInDiscards) as ifInDiscards,
        (curr.ifInErrors - prev.ifInErrors) as ifInErrors,
        (curr.ifInUnknownProtos - prev.ifInUnknownProtos) as ifInUnknownProtos ,
        (curr.ifOutOctets  - prev.ifOutOctets) as ifOutOctets ,
        (curr.ifOutUcastPkts - prev.ifOutUcastPkts) as ifOutUcastPkts ,
        (curr.ifOutNUcastPkts - prev.ifOutNUcastPkts) as ifOutNUcastPkts ,
        (curr.ifOutDiscards - prev.ifOutDiscards) as ifOutDiscards,
        (curr.ifOutErrors - prev.ifOutErrors) as ifOutErrors
         from
        (select *
        from
            ( select     datatime,
                        nodename,
                        dense_RANK() OVER ( PARTITION BY nodename ORDER BY datatime desc) as row_num,
                        ifOutBroadcastPkts,
                        ifHCInOctets,
                        ifInMulticastPkts,
                        ifOutMulticastPkts,
                        ifHCInUcastPkts,
                        ifHCInMulticastPkts,
                        ifInBroadcastPkts,
                        ifHCInBroadcastPkts,
                        ifHCOutOctets,
                        ifHCOutUcastPkts,
                        ifHCOutMulticastPkts,
                        ifHCOutBroadcastPkts,
                        ifIndex,
                        ifType,
                        ifMtu,
                        ifSpeed,
                        ifAdminStatus,
                        ifOperStatus,
                        ifLastChange,
                        ifInOctets,
                        ifInUcastPkts,
                        ifInNUcastPkts,
                        ifInDiscards,
                        ifInErrors,
                        ifInUnknownProtos,
                        ifOutOctets,
                        ifOutUcastPkts,
                        ifOutNUcastPkts,
                        ifOutDiscards,
                        ifOutErrors,
                        ifOutQLen
                        from dc.mpbn_ifentry_custom_one_min_new ) as a
            where row_num = 1
            order by nodename,ifIndex,row_num) as curr
    left join (select *
                from ( select datatime,
                        nodename,

                        dense_RANK() OVER ( PARTITION BY nodename ORDER BY datatime desc) as row_num,
                        ifOutBroadcastPkts,
                        ifHCInOctets,
                        ifInMulticastPkts,
                        ifOutMulticastPkts,
                        ifHCInUcastPkts,
                        ifInBroadcastPkts,
                        ifHCInMulticastPkts,
                        ifHCInBroadcastPkts,
                        ifHCOutOctets,
                        ifHCOutUcastPkts,
                        ifHCOutMulticastPkts,
                        ifHCOutBroadcastPkts,
                        ifIndex,
                        ifType,
                        ifMtu,
                        ifSpeed,
                        ifAdminStatus,
                        ifOperStatus,
                        ifLastChange,
                        ifInOctets,
                        ifInUcastPkts,
                        ifInNUcastPkts,
                        ifInDiscards,
                        ifInErrors,
                        ifInUnknownProtos,
                        ifOutOctets,
                        ifOutUcastPkts,
                        ifOutNUcastPkts,
                        ifOutDiscards,
                        ifOutErrors,
                        ifOutQLen
                from     dc.mpbn_ifentry_custom_one_min_new ) as a
                where row_num =2 
                order by nodename,ifIndex,row_num) as prev
        on curr.nodename = prev.nodename
        and curr.ifIndex = prev.ifIndex";
$connect = sasql_connect($con_str) or die("Cannot connect to the database");
sasql_query($connect,$query_string)
?>