<?php
ini_set('max_execution_time', 100);
$con_str = "Data Source=dwhdb; Uid=dba; Pwd=sql;";
$query_string = "   insert into dc.trig_mpbn_delta_values 
    select curr.datatime, 
      curr.nodename, 
      curr.ifIndex, 
      curr.ifType, 
      curr.ifMtu, 
      curr.ifSpeed, 
      curr.ifHighSpeed, 
      curr.ifAdminStatus, 
      curr.ifOperStatus, 
      curr.ifDescr,
      curr.ifPhysAddress, 
      curr.ifname , 
      curr.ifLastChange, 
      curr.ifOutQLen, 
      ifInMulticastPkts=(curr.ifInMulticastPkts-prev.ifInMulticastPkts), 
      ifInBroadcastPkts=(curr.ifInBroadcastPkts-prev.ifInBroadcastPkts), 
      ifOutMulticastPkts=(curr.ifOutMulticastPkts-prev.ifOutMulticastPkts), 
      ifOutBroadcastPkts=(curr.ifOutBroadcastPkts-prev.ifOutBroadcastPkts), 
      ifHCInOctets=(curr.ifHCInOctets-prev.ifHCInOctets), 
      ifHCInUcastPkts=(curr.ifHCInUcastPkts-prev.ifHCInUcastPkts), 
      ifHCInMulticastPkts=(curr.ifHCInMulticastPkts-prev.ifHCInMulticastPkts), 
       ifHCInBroadcastPkts=(curr.ifHCInBroadcastPkts-prev.ifHCInBroadcastPkts), 
      ifHCOutOctets=(curr.ifHCOutOctets-prev.ifHCOutOctets), 
      ifHCOutUcastPkts=(curr.ifHCOutUcastPkts-prev.ifHCOutUcastPkts), 
      ifHCOutMulticastPkts=(curr.ifHCOutMulticastPkts-prev.ifHCOutMulticastPkts), 
      ifHCOutBroadcastPkts=(curr.ifHCOutBroadcastPkts-prev.ifHCOutBroadcastPkts), 
      ifInOctets=(curr.ifInOctets-prev.ifInOctets), 
      ifInUcastPkts=(curr.ifInUcastPkts-prev.ifInUcastPkts), 
      ifInNUcastPkts=(curr.ifInNUcastPkts-prev.ifInNUcastPkts), 
      ifInDiscards=(curr.ifInDiscards-prev.ifInDiscards), 
       ifInErrors=(curr.ifInErrors-prev.ifInErrors), 
      ifInUnknownProtos=(curr.ifInUnknownProtos-prev.ifInUnknownProtos), 
      ifOutOctets=(curr.ifOutOctets-prev.ifOutOctets), 
      ifOutUcastPkts=(curr.ifOutUcastPkts-prev.ifOutUcastPkts), 
      ifOutNUcastPkts=(curr.ifOutNUcastPkts-prev.ifOutNUcastPkts), 
      ifOutDiscards=(curr.ifOutDiscards-prev.ifOutDiscards), 
      ifOutErrors=(curr.ifOutErrors-prev.ifOutErrors) 
      from(select * 
           from(select datatime, 
              nodename, 
              row_num=dense_RANK() over(partition by nodename order by datatime desc), 
              ifOutBroadcastPkts, 
              ifHCInOctets,
            ifPhysAddress, 
              ifname , 
 
              ifInMulticastPkts, 
              ifOutMulticastPkts, 
              ifHCInUcastPkts, 
              ifHCInMulticastPkts, 
              ifInBroadcastPkts, 
              ifHCInBroadcastPkts, 
              ifHCOutOctets, 
              ifHCOutUcastPkts, 
              ifHCOutMulticastPkts, 
              ifHCOutBroadcastPkts, 
              ifIndex, 
              ifType, 
              ifMtu, 
              ifSpeed, 
              ifHighSpeed, 
              ifAdminStatus, 
              ifOperStatus, 
            ifDescr,
               ifLastChange, 
              ifInOctets, 
              ifInUcastPkts, 
              ifInNUcastPkts, 
             ifInDiscards, 
               ifInErrors, 
              ifInUnknownProtos, 
              ifOutOctets, 
              ifOutUcastPkts, 
             ifOutNUcastPkts, 
              ifOutDiscards, 
              ifOutErrors, 
              ifOutQLen 
             from dc.mpbn_ifentry_custom_one_min_new) as a 
          where row_num = 1 
          order by nodename asc,ifIndex asc,row_num asc) as curr 
        left outer join(select * 
          from(select datatime, 
             nodename, 
              row_num=dense_RANK() over(partition by nodename order by datatime desc), 
              ifOutBroadcastPkts, 
              ifHCInOctets, 
              ifInMulticastPkts, 
              ifOutMulticastPkts, 
              ifHCInUcastPkts, 
             ifInBroadcastPkts, 
              ifHCInMulticastPkts, 
              ifHCInBroadcastPkts, 
              ifHCOutOctets, 
              ifHCOutUcastPkts, 
              ifHCOutMulticastPkts, 
              ifHCOutBroadcastPkts, 
              ifIndex, 
              ifType, 
              ifMtu, 
              ifSpeed, 
              ifAdminStatus, 
              ifOperStatus, 
              ifLastChange, 
              ifInOctets, 
              ifInUcastPkts, 
              ifInNUcastPkts, 
              ifInDiscards, 
              ifInErrors, 
              ifInUnknownProtos, 
              ifOutOctets, 
              ifOutUcastPkts, 
              ifOutNUcastPkts,              ifOutDiscards,              ifOutErrors, 
              ifOutQLen 
              from dc.mpbn_ifentry_custom_one_min_new) as a 
          where row_num = 2 
          order by nodename asc,ifIndex asc,row_num asc) as prev 
        on curr.nodename = prev.nodename 
       and curr.ifIndex = prev.ifIndex ";
$connect = sasql_connect($con_str) or die("Cannot connect to the database");
sasql_query($connect,$query_string);
 $url1=$_SERVER['REQUEST_URI']; 
 header("Refresh: 120; URL=$url1");
 echo $url;
?>